- README.md
READMEに自分の名前を入れた
https://github.com/quest-academia/qa-rails-ec-training-rose/issues/41
> #41 プルリク説明動画視聴、READMEに氏名記入（Tatty）

- db/seeds.rb
seed.rbにuserとuser_classificationの初期データを投入して　rails db:seedを実施。
https://github.com/quest-academia/qa-rails-ec-training-rose/issues/29
seed.rb の記載の仕方
コンソール上で.allで値を取得してデータが格納されていることを確認しました。
https://qiita.com/takehanKosuke/items/79a66751fe95010ea5ee
https://qiita.com/dogabon20/items/6c77d3ec07376c91b373
> #29 データ投入 Seed Users関連

- app/models/order.rb
- app/models/order_detail.rb
- app/models/shipment_status.rb
- db/migrate/20210707163407_create_orders.rb
- db/migrate/20210707164033_create_shipment_statuses.rb
- db/migrate/20210707164540_create_order_details.rb
- db/schema.rb
order関連各種モデルの作成とschemaファイルを更新致しました。
https://github.com/quest-academia/qa-rails-ec-training-rose/issues/31
>  #31 DB構築 Migration Orders関連

- app/models/user.rb
- db/seeds.rb
- seed.rbにProduct関連のデータを投入
https://github.com/quest-academia/qa-rails-ec-training-rose/issues/28
> #28 データ投入 Seed Products関連

- app/controllers/users_controller.rb
- app/views/users/show.html.erb
- config/application.rb
- config/routes.rb
ユーザー情報画面を作成しました。
ユーザーのデータ(seed.rbの初期データ）を取得し、idを指定して表示できるようにしました。
https://github.com/quest-academia/qa-rails-ec-training-rose/issues/24
http://localhost:3000/users/:id で画面にユーザー情報が表示されることは確認。
> #24 ユーザー情報画面作成

- Gemfile
- Gemfile.lock
- app/models/user.rb
- db/migrate/20210705142301_create_users.rb
- db/migrate/20210719134052_rename_password_column_to_users.rb
- db/schema.rb
- パスワードを保存する際にハッシュ化を使いより安全にパスワードをDBに保管できるようにする。
- https://github.com/quest-academia/qa-rails-ec-training-rose/issues/23
- https://qiita.com/kents1002/items/3015d60b91e6b03d5ffa
> #23 セキュアなパスワードの実装

- .rubocop.yml
- Rakefile
- app/controllers/products_controller.rb
- app/controllers/users_controller.rb
- app/mailers/application_mailer.rb
- app/models/user.rb
- app/models/user_classification.rb
- db/seeds.rb
- test/test_helper.rb
- rubocop実行時の警告文を出ないようにした
- rubocopの全ての指摘に対応した
Rakefileとかtest_helperなど、rubocop対象外にしてもよさそうなファイルも修正しておりますが、今回限りのことなのでExclude設定はせずそのまま対応いたしました。
- [ x ] 動作確認は実行した?
> rubocop指摘修正

- app/controllers/users_controller.rb
- app/views/users/edit.html.erb
editアクションを作成して、edit.html.erbにユーザー情報修正画面を実装しました
https://github.com/quest-academia/qa-rails-ec-training-rose/issues/19
色々ググりました今後のupdate、delete機能を考慮するとform_forなどで実装すべきだったのかどうか不安です。
右上の他ページへのリンク機能は別課題があったので実装していないです。
> #19 ユーザー情報修正画面実装

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/custom.scss
- app/controllers/products_controller.rb
- app/views/kaminari/_first_page.html.erb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_last_page.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/kaminari/_prev_page.html.erb
- app/views/products/index.html.erb
- config/application.rb
- config/locales/ja.yml
- https://github.com/quest-academia/qa-rails-ec-training-rose/issues/11
- https://qiita.com/d_nagano1002/items/fd90340c50324e845fe1
> #11 商品検索画面(検索ロジック以外)

- app/controllers/sessions_controller.rb
- app/views/sessions/new.html.erb
- config/routes.rb
#15 ログイン画面の実装を行いました。
https://github.com/quest-academia/qa-rails-ec-training-rose/issues/15
https://qiita.com/d0ne1s/items/7c4d2be3f53e34a9dec7
> #15 ログイン画面の実装

- app/assets/stylesheets/custom.scss
フッターの位置を固定するためにcssを追加しました。
https://github.com/quest-academia/qa-rails-ec-training-rose/issues/68
> #68 フッター位置を固定 

- app/helpers/application_helper.rb
- app/views/layouts/_footer.html.erb
- app/views/layouts/_header.html.erb
- app/views/layouts/application.html.erb
- app/views/orders/show.html.erb
- app/views/products/index.html.erb
- app/views/products/show.html.erb
- app/views/sessions/new.html.erb
- app/views/users/edit.html.erb
- app/views/users/show.html.erb
- htmlファイルを共通化しレイアウトを各ページ揃える
- ※ 注文詳細とログイン画面がマージされたら最新のdevelopを取り込みファイルを修正すること
- https://github.com/quest-academia/qa-rails-ec-training-rose/issues/21
- https://www.javadrive.jp/rails/template/index4.html
> #21 htmlファイルの共通化

- app/controllers/products_controller.rb
- app/models/product.rb
- app/views/products/index.html.erb
・商品検索ロジックを実装
・カテゴリーによる絞り込みロジックも実装
https://github.com/quest-academia/qa-rails-ec-training-rose/issues/6
https://pikawaka.com/rails/form_with
https://pikawaka.com/rails/where
> #6 商品検索画面(検索ロジック)

- app/assets/stylesheets/custom.scss
- app/controllers/users_controller.rb
- app/views/layouts/_error_messages.html.erb
- app/views/layouts/_flash_messages.html.erb
- app/views/layouts/application.html.erb
- app/views/users/edit.html.erb
ユーザー情報更新機能を実装しました。
https://github.com/quest-academia/qa-rails-ec-training-rose/issues/17
> #17　ユーザー情報更新機能

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/helpers/sessions_helper.rb
- app/views/layouts/_header.html.erb
- app/views/sessions/new.html.erb
- config/routes.rb
- ログイン、ログアウト処理を実装
- https://github.com/quest-academia/qa-rails-ec-training-rose/issues/14
- https://railstutorial.jp/chapters/log_in_log_out?version=4.2
> #14 ログイン、ログアウト処理 

- Gemfile
- Gemfile.lock
- config/application.rb
- config/locales/models/ja.yml
・gemfileにrails-i18nを追加
・config/locales/models/に、ja.ymlというファイルを作成し日本語対応表を作成
・config/application.rbに読み込み用の一文を追加
効いているかの検証はコンソール上で行いました。
https://github.com/quest-academia/qa-rails-ec-training-rose/issues/16
前期の反省を踏まえ、全モデルに対応させました。しかし、複数モデルを並べているソース記事は以下のものしか見つけることができず、正しいかどうかが不安です。他に良い書き方があれば、教えていただけると幸いです。
https://losenotime.jp/validation-message/
https://qiita.com/Ushinji/items/242bfba84df7a5a67d5b
> #16 エラーメッセージの日本語化

- app/controllers/orders_controller.rb
- app/controllers/users_controller.rb
- app/helpers/sessions_helper.rb
- ログイン、ログアウト時でアクセス制限を掛ける為認可機能を実装
- https://github.com/quest-academia/qa-rails-ec-training-rose/issues/13
- https://railstutorial.jp/chapters/updating_and_deleting_users?version=4.2#cha-updating_showing_and_deleting_users
> #13 認可処理機能

- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/views/layouts/_header.html.erb
- app/views/sessions/new.html.erb
- config/routes.rb
・SessionsControllerに新しいアクション`guest_login`, `guest_create`を準備
・ゲストがメールアドレス・パスワードを変更できないように`users#update`で条件分岐
・「ゲストログイン」のボタン配置（①ログイン画面の「ログイン」下、②ヘッダーの「ログイン」右）
https://github.com/quest-academia/qa-rails-ec-training-rose/issues/1
・`guest_logion`と`guest_create`はひとまとめにしていましたが、rubocopに長いと言われたため２つに分解しました。
・ゲストのユーザーidは一般ユーザーと重複しないようにするため、500（仮）と明示してcreateさせています。
https://qiita.com/take18k_tech/items/35f9b5883f5be4c6e104
> #1 ゲストログイン

- app/controllers/sessions_controller.rb
- app/controllers/staticpages_controller.rb
- app/helpers/sessions_helper.rb
- app/views/staticpages/home.html.erb
- config/routes.rb
・StaticPagesコントローラ作成
・routesにrootとしてパス追加
・viewでログインの有無で表示する画面と表示しない画面を条件分岐で分ける
・「ログイン」・「新規登録」のボタンのリンクを設定。
・「ゲストログイン」、「認可処理」のメソッドの遷移先に`root_path`を設定
https://github.com/quest-academia/qa-rails-ec-training-rose/issues/10
> #10 TOPページ画面

- app/controllers/carts_controller.rb
- app/controllers/orders_controller.rb
- app/views/carts/show.html.erb
- app/views/layouts/_header.html.erb
- app/views/orders/perchase_completed.html.erb
- app/views/products/show.html.erb
- config/routes.rb
- sessionを使用しカートへ商品を追加、削除する機能を実装
- https://github.com/quest-academia/qa-rails-ec-training-rose/issues/3
- 以下二箇所のエラーが起きており.rubocop.ymlの文字数制限の設定を変更する必要があるようですが添付記事のように処理して宜しいのでしょうか。
https://qiita.com/m6mmsf/items/530c3c11db56f1b42dcf
- app/controllers/carts_controller.rb:21:3: C: Metrics/AbcSize: Assignment Branch Condition size for add_cart is too high. [<5, 34, 5> 34.73/24]
def add_cart ...
^^^^^^^^^^^^
- app/controllers/orders_controller.rb:12:3: C: Metrics/AbcSize: Assignment Branch Condition size for create is too high. [<3, 30, 2> 30.22/24]
def create ...
^^^^^^^^^^
- https://qiita.com/sashun/items/5e36e794daa1a61b5ed2
> #3 カート機能実装

- config/database.yml
> herokuデプロイのためにdatabase.yml修正

- app/controllers/carts_controller.rb
`carts.controller.rb` のRubocopの警告対応 
インデントのずれを修正
>  rubocop警告対応を実施

- app/controllers/orders_controller.rb
- app/controllers/users_controller.rb
- app/helpers/sessions_helper.rb
- app/views/orders/show.html.erb
#4 注文キャンセル機能の再プルリク・Rubocop指摘対応・correct_userの指摘対応
https://github.com/quest-academia/qa-rails-ec-training-rose/issues/4
全て解決いたしました。
> #4 注文キャンセル機能・Rubocop指摘対応・correct_userの修正対応
